[tool.poetry]
name = "iot_inspector_client"
version = "0.1.0"
description = "IoT Inspector API client"
homepage = "https://www.iot-inspector.com/"
authors = ["IoT Inspector <support@iot-inspector.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"
httpx = "^0.17.0"
pydantic = "^1.8.1"
Authlib = "^0.15.3"
importlib-resources = "^5.1.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
